#!/usr/bin/env bash
#
# This script is used to manage the ~/Download folder of a user. It will be the
# handler of inotify notifications and will move a downloaded file into
# subfolders under the ~/Download folder named after the file's extension.

folders=("Documents" "Music" "Compressed" "Programs" "Scripts" "Pictures" "Video" "Torrent Files")
set -euo pipefail
#set -x
cd ~/Downloads || exit 1

declare -ri MOVED_TO=128
declare -ri CREATE=256

function move_per_filetype() {
  local file="$1"

  local file_extension
  file_extension="${file##*.}"

  local user="$(stat -c %U .)"

  if [[ "${file_extension}" == '' ]]; then
    return
  fi
for default_dirs in "${folders[@]}"
	do
		if [[ ! -e "${default_dirs}" ]]
			then
				mkdir -p "${default_dirs}" > /dev/null 2>&1
			else
				:
		fi
	done

  case "${file_extension}" in
     'epub'| 'odt' | 'pptx' | 'ppt' | 'odf' | 'doc' | 'docx' | 'pdf' | 'txt' | 'xlsx' )
      sudo -u "$user" mv -f "$file" "Documents/"
      ;;
      'mp4'| 'mkv')
      sudo -u "$user" mv -f "$file" "Video/"
      ;;
      'zip'|'rar'|'bz2' | 'gz' | 'tar' | 'zst' | 'tbz2' | 'tgz' | 'Z' | '7z' | 'xz' | 'ex' | 'tar.bz2' | 'tar.gz' | 'tar.xz' | 'iso'| 'apk')
      sudo -u "$user" mv -f "$file" "Compressed/"
      ;;
     'deb'| 'rpm' | 'exe' | 'AppImage' | 'dmg')
      sudo -u "$user" mv -f "$file" "Programs/"
      ;;
      'mp3'| 'mpa' | 'wav')
      sudo -u "$user" mv -f "$file" "Music/"
      ;;
      'hs'| 'sh'| 'pl'| 'py'| 'rb'| 'jl'| 'r'| 'js'| 'bash')
      sudo -u "$user" mv -f "$file" "Scripts/"
      ;;
      'png'| 'jpg'| 'jpeg' | 'gif' | 'tif' | 'tiff' | 'bpm' | 'svg')
      sudo -u "$user" mv -f "$file" "Pictures/"
      ;;
      'torrent')
      sudo -u "$user" mv -f "$file" "Torrent Files/"
      ;;
    *)
	sudo -u "$user" mv -f "$file" "Others/"    
      return
      ;;
  esac
}


function download_watcher() {
  local file
  local event

  event="${WENDY_EVENT-$1}"
  file="${WENDY_INODE-$2}"

  case "$event" in
    256|CREATE)
      move_per_filetype "$file"
      ;;
    128|MOVED_TO)
      WENDY_EVENT=256
      at now + 3 minutes <<< "${BASH_SOURCE[0]} ${event} ${file}"
      ;;
  esac
}


download_watcher "$@"

